apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstor-example
spec:
  selector:
    matchLabels:
      app: cstor-example
  template:
    metadata:
      labels:
        app: cstor-example
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: vol-html
            - mountPath: "/var/log/nginx"
              name: vol-logs
      volumes:
      - name: vol-html
        persistentVolumeClaim:
          claimName: cstor-vol1
      - name: vol-logs
        persistentVolumeClaim:
          claimName: cstor-vol2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cstor-vol1
spec:
  storageClassName: openebs-sparse-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: 1950Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cstor-vol2
spec:
  storageClassName: openebs-sparse-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: 50Mi
